#ifndef STM32_SYSCFG_HW_H
#define STM32_SYSCFG_HW_H

#include "stm32_mmio.h"

#define SYSCFG_BASE             0x40010000UL

#define SYSCFG_MEMRMP_OFFSET    0x00
#define SYSCFG_EXTICR1_OFFSET   0x04
#define SYSCFG_EXTICR2_OFFSET   0x08
#define SYSCFG_EXTICR3_OFFSET   0x0C
#define SYSCFG_EXTICR4_OFFSET   0x10
#define SYSCFG_SCSR_OFFSET      0x18
#define SYSCFG_CFGR2_OFFSET     0x1C
#define SYSCFG_SWPR_OFFSET      0x20
#define SYSCFG_SKR_OFFSET       0x24

#define SYSCFG_MEMRMP         REG32(SYSCFG_BASE + SYSCFG_MEMRMP_OFFSET)
/* n = 0..3 for EXTICR1-4 (zero-based index for pin-group) */
#define SYSCFG_EXTICR(n)      REG32(SYSCFG_BASE + SYSCFG_EXTICR1_OFFSET + ((n) * (0x04U)))
#define SYSCFG_SCSR           REG32(SYSCFG_BASE + SYSCFG_SCSR_OFFSET)
#define SYSCFG_CFGR2          REG32(SYSCFG_BASE + SYSCFG_CFGR2_OFFSET)
#define SYSCFG_SWPR           REG32(SYSCFG_BASE + SYSCFG_SWPR_OFFSET)
#define SYSCFG_SKR            REG32(SYSCFG_BASE + SYSCFG_SKR_OFFSET)

#endif /* STM32_SYSCFG_HW_H */