#ifndef SMT32_RCC_HW
#define SMT32_RCC_HW

#include "stm32_gpio_hw.h"

#define RCC_BASE             0x40021000UL

#define RCC_CR_OFFSET        0x00
#define RCC_CFGR_OFFSET      0x08
#define RCC_AHB2ENR_OFFSET   0x4C
#define RCC_APB1RSTR1_OFFSET 0x38
#define RCC_APB1ENR1_OFFSET  0x58
#define RCC_APB2ENR_OFFSET   0x60
#define RCC_CCIPR_OFFSET     0x88
#define RCC_APB1ENR2_OFFSET  0x5C

#define RCC_CR               REG32(RCC_BASE + RCC_CR_OFFSET)
#define RCC_CFGR             REG32(RCC_BASE + RCC_CFGR_OFFSET)
#define RCC_AHB2ENR          REG32(RCC_BASE + RCC_AHB2ENR_OFFSET)
#define RCC_APB1RSTR1        REG32(RCC_BASE + RCC_APB1RSTR1_OFFSET)
#define RCC_APB1ENR1         REG32(RCC_BASE + RCC_APB1ENR1_OFFSET)
#define RCC_APB2ENR          REG32(RCC_BASE + RCC_APB2ENR_OFFSET)
#define RCC_CCIPR            REG32(RCC_BASE + RCC_CCIPR_OFFSET)
#define RCC_APB1ENR2         REG32(RCC_BASE + RCC_APB1ENR2_OFFSET)

#endif
